### PR TITLE
Update _bp.pyx

### PR DESCRIPTION
**Pull request by esayyari**
Changing some method definitions from cdef to cpdef, so we have access to those methods from python

### CODE REVIEW

**Comment by wasade** [comment]
:+1:

Looks like travis isn't running -- I'll see what's going on there

**Comment by wasade** [comment]
Thanks for that merge. Travis is running again, looks like there are some issues (https://travis-ci.com/github/wasade/improved-octo-waddle/jobs/363453203). I think it's just that the `.pxd` file also needs to be updated

**Comment by wasade** [comment]
was hopeful py37 would work but it doesn't due to dependencies (https://travis-ci.com/github/wasade/improved-octo-waddle/jobs/363457462). Can you remove the py37 entry from .travis.yml? that i think should do it

**Comment by esayyari** [comment]
Thanks! Travis is happy now.

**Comment by wasade** [comment]
Thanks!

**Pull request merged**
